In [12]:
import pandas as pd

# Replace with your actual file path
file_path = r"C:\ML projects\ACL tears\DATASET\combined\metadata.csv"

df = pd.read_csv(file_path)

In [10]:
df

,patient_id,filename,label,label_name,num_slices,height,width,series
0,150 NORMAL ACL,150_NORMAL_ACL.npz,0,NORMAL,50,224,224,PDW_mDIXOM_SAG
1,199 NORMAL ACL,199_NORMAL_ACL.npz,0,NORMAL,50,224,224,PDW_mDIXOM_SAG
2,214 NORMAL ACL BONE BRUISE,214_NORMAL_ACL_BONE_BRUISE.npz,0,NORMAL,50,224,224,PDW_mDIXOM_SAG
3,219 NORMAL ACL,219_NORMAL_ACL.npz,0,NORMAL,50,224,224,PDW_mDIXOM_SAG
4,225 NORMAL ACL MENISCUS,225_NORMAL_ACL_MENISCUS.npz,0,NORMAL,50,224,224,PDW_mDIXOM_SAG
...,...,...,...,...,...,...,...,...
461,448 1 ACL BONE BRUISE,448_1_ACL_BONE_BRUISE.npz,1,PARTIAL,50,224,224,PDW_mDIXOM_SAG
462,462 POST OP ACL,462_POST_OP_ACL.npz,1,PARTIAL,50,224,224,PDW_mDIXOM_SAG
463,463 1 ACL BONE BRUISE,463_1_ACL_BONE_BRUISE.npz,1,PARTIAL,50,224,224,PDW_mDIXOM_SAG
464,471 POST OP ACL,471_POST_OP_ACL.npz,1,PARTIAL,50,224,224,PDW_mDIXOM_SAG
465,483 POST OP ACL,483_POST_OP_ACL.npz,1,PARTIAL,50,224,224,PDW_mDIXOM_SAG

In [13]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df

,patient_id,filename,label,label_name,num_slices,height,width,source
0,150 NORMAL ACL,150_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
1,199 NORMAL ACL,199_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
2,214 NORMAL ACL BONE BRUISE,214_NORMAL_ACL_BONE_BRUISE.npz,0,NORMAL,50,224,224,Priyank_Saxena
3,219 NORMAL ACL,219_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
4,225 NORMAL ACL MENISCUS,225_NORMAL_ACL_MENISCUS.npz,0,NORMAL,50,224,224,Priyank_Saxena
5,226 NORMAL ACL,226_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
6,251 NORMAL ACL,251_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
7,259 NORMAL ACL BONE BRUISE,259_NORMAL_ACL_BONE_BRUISE.npz,0,NORMAL,50,224,224,Priyank_Saxena
8,267 NORMAL ACL MENISCUS,267_NORMAL_ACL_MENISCUS.npz,0,NORMAL,50,224,224,Priyank_Saxena
9,268 NORMAL ACL,268_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
10,303 NORMAL ACL,303_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
11,317 NORMAL ACL,317_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
12,356 NORMAL ACL BONE BRUISE,356_NORMAL_ACL_BONE_BRUISE.npz,0,NORMAL,50,224,224,Priyank_Saxena
13,358 NORMAL ACL,358_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
14,360 NORMAL ACL,360_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
15,364 NORMAL ACL,364_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
16,377 NORMAL ACL,377_NORMAL_ACL.npz,0,NORMAL,60,224,224,Priyank_Saxena
17,378 NORMAL ACL,378_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
18,399 NORMAL ACL BONE BRUISE,399_NORMAL_ACL_BONE_BRUISE.npz,0,NORMAL,50,224,224,Priyank_Saxena
19,414 NORMAL ACL,414_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
20,418 NORMAL ACL,418_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
21,423 NORMAL ACL BONE BRUISE,423_NORMAL_ACL_BONE_BRUISE.npz,0,NORMAL,50,224,224,Priyank_Saxena
22,430 NORMAL ACL,430_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
23,433 NORMAL ACL,433_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
24,435 NORMAL ACL BONE BRUISE,435_NORMAL_ACL_BONE_BRUISE.npz,0,NORMAL,50,224,224,Priyank_Saxena
25,441 NORMAL ACL,441_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
26,451 NORMAL ACL,451_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
27,459 NORMAL ACL BONE BRUISE,459_NORMAL_ACL_BONE_BRUISE.npz,0,NORMAL,50,224,224,Priyank_Saxena
28,482 NORMAL ACL,482_NORMAL_ACL.npz,0,NORMAL,50,224,224,Priyank_Saxena
29,001 ACL,001_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
30,003 ACL PCL MENISCUS,003_ACL_PCL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
31,010ACL MEDIAL MENISCUS,010ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
32,013 ACL,013_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
33,015 ACL MEDIAL MENISCUS,015_ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
34,017 ACL,017_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
35,018 ACL LATERAL MENISCUS,018_ACL_LATERAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
36,019 ACL LATERAL MENISCUS,019_ACL_LATERAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
37,020 ACL,020_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
38,021 ACL,021_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
39,022 ACL LATERAL MENISCUS,022_ACL_LATERAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
40,024 ACL MEDIAL MENISCUS,024_ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
41,029 ACL PCL,029_ACL_PCL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
42,030 ACL MEDIAL MENISCUS,030_ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
43,033 ACL,033_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
44,034 ACL,034_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
45,035 ACL MEDIAL MENISCUS,035_ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
46,036 ACL,036_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
47,045 ACL,045_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
48,048 ACL,048_ACL.npz,2,COMPLETE,56,224,224,Priyank_Saxena
49,049 ACL,049_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
50,050 ACL,050_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
51,051 ACL,051_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
52,052 ACL LATERAL MENISCUS,052_ACL_LATERAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
53,056 ACL,056_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
54,057 ACL,057_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
55,058 ACL,058_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
56,060 ACL,060_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
57,062 ACL MEDIAL LATERAL MENISCUS,062_ACL_MEDIAL_LATERAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
58,063 ACL,063_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
59,064 ACL PCL,064_ACL_PCL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
60,065 ACL,065_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
61,073 ACL,073_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
62,074 ACL,074_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
63,075 ACL PCL,075_ACL_PCL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
64,076 ACL,076_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
65,077 ACL,077_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
66,082 ACL MEDIAL LATERAL MENISCUS,082_ACL_MEDIAL_LATERAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
67,084 ACL MEDIAL MENISCUS,084_ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
68,087 ACL,087_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
69,088 ACL,088_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
70,089 ACL,089_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
71,090 ACL,090_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
72,094 ACL,094_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
73,095 ACL,095_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
74,096 ACL,096_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
75,097 ACL,097_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
76,098 ACL,098_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
77,099 ACL,099_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
78,100 ACL,100_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
79,101 ACL,101_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
80,103 ACL,103_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
81,104 ACL,104_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
82,106 ACL,106_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
83,107 ACL,107_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
84,111 ACL,111_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
85,112 ACL,112_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
86,113 ACL,113_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
87,114 ACL,114_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
88,115 ACL,115_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
89,124 ACL,124_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
90,126 ACL,126_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
91,127 ACL LATERAL MENISCUS,127_ACL_LATERAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
92,128 ACL MEDIAL MENISCUS,128_ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
93,129 ACL MEDIAL MENISCUS,129_ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
94,130 ACL,130_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
95,132 ACL,132_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
96,133 ACL,133_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
97,134 ACL LATERAL MENISCUS,134_ACL_LATERAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
98,139 ACL,139_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
99,140 ACL,140_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
100,141 ACL,141_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
101,145 ACL LATERAL MENISCUS,145_ACL_LATERAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
102,146 ACL,146_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
103,153 ACL 3 MENSICUS,153_ACL_3_MENSICUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
104,155 ACL 3,155_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
105,156 ACL 3 MENISCUS,156_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
106,157 ACL 3 MENISCUS,157_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
107,158 ACL 3,158_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
108,159 ACL 3 MENISCUS BONE BRUISE,159_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,60,224,224,Priyank_Saxena
109,163 ACL 3,163_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
110,164 ACL 4 MENISCUS,164_ACL_4_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
111,165 ACL 3 PCL BONE BRUISE,165_ACL_3_PCL_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
112,166 ACL 3 BONE BRUISE MENISCUS,166_ACL_3_BONE_BRUISE_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
113,167 ACL 3 MENISCUS BONE BRUISE,167_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
114,168 ACL 3 MENISCUS,168_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
115,169 ACL 3,169_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
116,170 ACL 3,170_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
117,171 ACL 3 MENISCUS,171_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
118,172 ACL 3 MENISCUS,172_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
119,174 ACL 3,174_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
120,175 ACL 3 MENISCUS BONE BRUISE,175_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
121,176 ACL 3 BONE BRUISE,176_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
122,178 ACL 3 MENISCUS BONE BRUISE,178_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,60,224,224,Priyank_Saxena
123,179 ACL 3 MENISCUS,179_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
124,180 ACL 3,180_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
125,182 ACL 3 BONE BRUISE,182_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
126,183 ACL 3 MENISCUS,183_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
127,184 ACL 3,184_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
128,185 ACL 3,185_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
129,186 ACL 3 MENISCUS BONE BRUISE,186_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,54,224,224,Priyank_Saxena
130,187 ACL 3 MENISCUS,187_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
131,189 ACL 3,189_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
132,190 ACL 3 MENISCUS,190_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
133,191 ACL 3,191_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
134,192 ACL 3 MENISCUS,192_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
135,193 ACL 3 BONE BRUISE,193_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
136,195 ACL 3,195_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
137,200 ACL 3,200_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
138,201 ACL 3,201_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
139,202 ACL 3,202_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
140,203 ACL 3 PCL MENISCUS,203_ACL_3_PCL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
141,205 ACL 3,205_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
142,206 ACL 3,206_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
143,207 ACL 3,207_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
144,208 ACL 3,208_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
145,209 ACL 3,209_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
146,210 ACL 3,210_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
147,211 ACL 3 MENISCUS,211_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
148,212 ACL 3,212_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
149,215 ACL 3 MENISCUS,215_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
150,216 ACL 3 MENISCUS,216_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
151,220 ACL 3 BONE BRUISE,220_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
152,221 ACL 3,221_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
153,222 ACL 3,222_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
154,223 ACL 3 BONE BRUISE,223_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
155,227 ACL 3,227_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
156,228 ACL 3 MENISCUS BONE BRUISE,228_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
157,230 ACL 3 BONE BRUISE,230_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
158,231 ACL 3,231_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
159,232 ACL,232_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
160,235 ACL,235_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
161,236 ACL,236_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
162,237 ACL MEDIAL MENISCUS,237_ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
163,238 ACL MEDIAL MENISCUS,238_ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
164,242 ACL,242_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
165,245 ACL MEDIAL MENISCUS,245_ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
166,246 ACL MEDIAL MENISCUS,246_ACL_MEDIAL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
167,248 ACL,248_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
168,249 ACL,249_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
169,250 ACL,250_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
170,253 ACL 3 MENISCUS,253_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
171,254 ACL 3,254_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
172,255 ACL 3 PCL MENISCUS,255_ACL_3_PCL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
173,256 ACL 3 MENISCUS,256_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
174,257 ACL 3 MENISCUS BONE BRUISE,257_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
175,258 ACL 3 PACL MENISCUS,258_ACL_3_PACL_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
176,261 ACL 3 BONE BRUISE,261_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
177,262 ACL 3 MENISCUS BONE BRUISE,262_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,56,224,224,Priyank_Saxena
178,263 ACL 3 BONE BRUISE,263_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
179,264 ACL 3,264_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
180,265 ACL 3,265_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
181,266 ACL 3 MENISCUS,266_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
182,270 ACL 3,270_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
183,271 ACL 3,271_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
184,272 ACL 3,272_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
185,273 ACL 3 MENISCUS BONE BRUISE,273_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
186,275 ACL 3,275_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
187,276 ACL 3 MENISCUS,276_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
188,277 ACL 3,277_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
189,280 ACL 3 MENISCUS,280_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
190,281 ACL 3 MENISCUS BONE BRUISE,281_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
191,282 ACL 3,282_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
192,285 ACL 3 BONE BRUISE,285_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
193,286 ACL 3 MENISCUS,286_ACL_3_MENISCUS.npz,2,COMPLETE,54,224,224,Priyank_Saxena
194,287 ACL 3 MENISCUS,287_ACL_3_MENISCUS.npz,2,COMPLETE,54,224,224,Priyank_Saxena
195,288 ACL 3 MENICUS BONE BRUISE,288_ACL_3_MENICUS_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
196,289 ACL 3,289_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
197,290 ACL 3 BOINE BRUISE,290_ACL_3_BOINE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
198,291 ACL 3,291_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
199,292 ACL 3,292_ACL_3.npz,2,COMPLETE,30,224,224,Priyank_Saxena
200,293 ACL 3 MENISCUS BONE BRUISE,293_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
201,294 ACL 3,294_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
202,296 ACL 3 MENISCUS,296_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
203,298 ACL 3 BONE BRUISE,298_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
204,299 ACL 3 MENISCUS,299_ACL_3_MENISCUS.npz,2,COMPLETE,60,224,224,Priyank_Saxena
205,300 ACL 3 BONE BRUISE MENISCUS,300_ACL_3_BONE_BRUISE_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
206,304 ACL 3 MENISCUS,304_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
207,306 ACL 3,306_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
208,308 ACL 3,308_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
209,311 ACL 3,311_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
210,312 ACL 3,312_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
211,313 ACL 3,313_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
212,314 ACL 3 MENISCUS,314_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
213,315 ACL 3,315_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
214,316 ACL 3 MENISCUS,316_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
215,318 ACL 3,318_ACL_3.npz,2,COMPLETE,56,224,224,Priyank_Saxena
216,321 ACL 3 MENISCUS,321_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
217,322 ACL 3 MENISCUS,322_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
218,323 ACL 3,323_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
219,324 ACL 3,324_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
220,325 ACL 3,325_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
221,327 ACL 3 BONE BRUISE,327_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
222,330 ACL 3 MENISCUS,330_ACL_3_MENISCUS.npz,2,COMPLETE,52,224,224,Priyank_Saxena
223,331 ACL 3,331_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
224,333 ACL 3,333_ACL_3.npz,2,COMPLETE,48,224,224,Priyank_Saxena
225,335 ACL 3,335_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
226,336 ACL 3 MENISCUS BONE BRUISE,336_ACL_3_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
227,337 ACL 3 BONE BRUISE,337_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
228,338 ACL 3,338_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
229,339 ACL 3 MENISCUS,339_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
230,340 ACL 3,340_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
231,341 ACL 3 BONE BRUISE,341_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
232,342 ACL 3,342_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
233,343 ACL 3,343_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
234,344 ACL 3,344_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
235,346 ACL 3,346_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
236,347 ACL 3,347_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
237,348 ACL 3,348_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
238,349 ACL 3,349_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
239,350 ACL 3 MUCOID DEGENERATION,350_ACL_3_MUCOID_DEGENERATION.npz,2,COMPLETE,50,224,224,Priyank_Saxena
240,351 ACL 3,351_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
241,352 ACL 3,352_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
242,353 ACL 3,353_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
243,357 ACL 3 MENISCUS,357_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
244,359 ACL 3,359_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
245,362 ACL 3 BONE BRUISE,362_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
246,363 ACL 3 BONE BRUISE,363_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
247,365 ACL 3,365_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
248,366 ACL 3,366_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
249,367 ACL 3,367_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
250,369 ACL 3,369_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
251,370 ACL 3 MENISCUS,370_ACL_3_MENISCUS.npz,2,COMPLETE,60,224,224,Priyank_Saxena
252,371 ACL 3 PCL MENISCUS BONE BRUISE,371_ACL_3_PCL_MENISCUS_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
253,372 ACL 3 PCL BONE BRUISE,372_ACL_3_PCL_BONE_BRUISE.npz,2,COMPLETE,56,224,224,Priyank_Saxena
254,373 ACL 3,373_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
255,374 ACL 3,374_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
256,376 ACL 3 MENISCUS,376_ACL_3_MENISCUS.npz,2,COMPLETE,48,224,224,Priyank_Saxena
257,379 ACL 3,379_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
258,380 ACL 3 MENISCUS,380_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
259,381 ACL 3,381_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
260,383 ACL 3,383_ACL_3.npz,2,COMPLETE,50,224,224,Priyank_Saxena
261,384 ACL 3 BONE BRUISE,384_ACL_3_BONE_BRUISE.npz,2,COMPLETE,50,224,224,Priyank_Saxena
262,385 ACL 3 MENISCUS,385_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena
263,386 3 ACL,386_3_ACL.npz,2,COMPLETE,50,224,224,Priyank_Saxena
264,387 ACL 3 MENISCUS,387_ACL_3_MENISCUS.npz,2,COMPLETE,50,224,224,Priyank_Saxena